version: "3.8"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - 3000:5173
    volumes:
      - type: bind
        source: "client/src"
        target: "/usr/app/src"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - 80:80
    volumes:
      - type: bind
        source: server/src
        target: /go/app/src
